import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { PaginationProvider } from "contexts/PaginationContext";
import Navbar from "ui/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PaginationProvider>
          {children}
        </PaginationProvider>
      </body>
    </html>
  );
}
